### PR TITLE
Add qbittorrent icon

### PR DESCRIPTION
**Pull request by varlesh**

### CODE REVIEW

**Comment by UriHerrera** [comment]
Feedback:

First, cool icons. Second _please clean the SVG documents_ they have a lot of unnecessary information in them.

Third, the shadows we use aren't complete black (#000) to alpha, check the other app icons for the shadow gradient.

**Comment by varlesh** [comment]
Ok )

**Comment by varlesh** [comment]
All updated.

**Comment by varlesh** [comment]
Why not merged?
Something you do not like?

**Comment by UriHerrera** [comment]
The qbittorrent logo looks quite _fat_, make the characters thinner.

**Comment by UriHerrera** [comment]
Stil look thick, and the qb are positioned different. Use some 4px or 6px wide obejcts.

**Comment by varlesh** [comment]
My English is very bad. Sorry, but I do not understand you :(
Can you merged and fix yourself ?

**Comment by varlesh** [comment]
Please chek :)

**Comment by s-kostyuk** [comment]
If commit 4cc0db8 is a response to #208 - please, move your icons from ``Breeze/apps/software-medium/`` to  ``Breeze/status/panel``. Otherwise they will not be found by Caffeine and will not be displayed.

Icon in the wild (placed to Breeze/status/panel):
caffeine1 caffeine2

**Comment by s-kostyuk** [comment]
Thanks for 713fb49

**Comment by DarkknightAK** [comment]
I made an review of the app icons and push them in #232 
sorry but I don't know how to contribute to your tree, .... hope it fit's for you.

I only push the app icons because kaffeine needs a little more work than only an system tree icon (some toolbar icons, ...)

thanks a lot for your contribution.

**Comment by s-kostyuk** [comment]
One small remark: that wasn't Kaffeine (media player) icon, it was a
Caffeine icon (sleep and screen off prevention app) :)

**Comment by DarkknightAK** [comment]
kaffeine has also an system tray icon ;-)

**Comment by varlesh** [comment]
Maybe close this request and add new for caffeine icons?

**Comment by DarkknightAK** [comment]
please

**Pull request closed without merging**
