### PR TITLE
missing firefox icons (gtk)

### PR DESCRIPTION
**Pull request by DarkknightAK**
before

after

before

after

### CODE REVIEW

**Comment by UriHerrera** [comment]
They probably should be in a seprate folder and not mixed with the ones used for K apps.

**Comment by DarkknightAK** [comment]
OK will add an additional folder. for amarok should I add an additional toolbar folder too? cause the namens are not amarok-xxx

**Comment by UriHerrera** [comment]
No that's a K app.

**Comment by DarkknightAK** [comment]
done as you describe. start with folder cleaning.

**Pull request merged**
