### PR TITLE
Added Choqok, KTorrent, and SMPlayer + others

### PR DESCRIPTION
**Pull request by Ken-Vermette**
The previous KTorrent icon is now the KGet icon; KTorrent now has its own unique icon.
Targets: #167, #155, and #108.

### CODE REVIEW

**Comment by UriHerrera** [comment]
* Akregator - it can do without the glasses.
* Ktorrent - I don't know how to relate the splashing concept to a torrent client. Perhaps just a simple sheet and an arrow?.
* SMPLayer - change the radial gradient to linear.

**Comment by Ken-Vermette** [comment]
Akregator - Ditched the glasses; good call, I couldn't shoehorn those things in, I should have dumped them earlier. I'll load it when you reply to the next points;
Ktorrent -  The concept is a play on the definition of "torrent", which can also be fast flowing stream of water ("torrent of water"); the previous icon was a waterfall landing in the "V" portion of the arrow, I wanted to capture that for Breeze since it was wonderfully creative and felt "brand-ish".  ;)
SMPlayer - There aren't any radial gradients... If you're looking at the "metal" of the projector wheel it's just a 3-stop linear gradient. Want me to change it to a 2-stop?

**Comment by Ken-Vermette** [comment]
Just added more icons. I'll specifically single-out Skrooge as an icon I'm personally unhappy with, I can't get it right. If it's not up to snuff I'll drop it.
This is also NOT the Kdenlive icon from the forums; now that I have a semblance of an idea what I'm doing here, this variant is much more in-line with the Breeze style.

**Comment by UriHerrera** [comment]
I thought I had merged your commit. I'll check the added icons.

**Comment by UriHerrera** [comment]
What's the `preferences-plugin` icon for?

The icon for Konqueror has the wrong name it says `konquerer`

Marble is a software like Google Earth right?, I'm not sure the compass more related to Webkit browsers fits there.

**Comment by Ken-Vermette** [comment]
The preferences-plugin icon is just a generic plugin icon used when configuring modular utilities. It was on the todo list, but it's more of a utility icon than one used in a specific place.
I'll correct the Konqueror name. I'm terminally unable to spell that correctly.
For marble, their current icon is exactly what I submitted, only tilted slightly upwards - but you aren't the first to compare it to Safari/Webkit/browser and I doubt you'll be the last. I'll break from the current design and try something new, if 2/2 people I see referencing that icon think it's for browsers it's a serious issue.
On an aside, I have some Calligra icons in the wings, but I'm not happy with them. I'll be trying to get them in before the freeze, just so you're aware; though I'll hold off until after the current pull since I both want time with them, and to avoid overextending this pull request.

**Pull request merged**
