### PR TITLE
Change Konversation icon

### PR DESCRIPTION
**Pull request by Sogatori**
Hey Uri,
as you know I worked with the konversation people. I finished my work and would like to propose the upstream change of the icon. What do you think? ;)

### CODE REVIEW

**Comment by UriHerrera** [comment]
I'd just say that you should use another green gradient.

**Comment by Sogatori** [comment]
Do you have preference? Brighter or darker?

**Comment by Sogatori** [comment]
Ok, I made the gradient flatter and while doing that used the green from the colour palette. What do you think?

**Comment by Sogatori** [comment]
Ok, I made the gradient flatter and while doing that used the green from the colour palette. What do you think?

**Comment by UriHerrera** [comment]
Hmm quite green, change it to the blue from the other icvons like Muon.

**Comment by Sogatori** [comment]
Ok, done.

**Pull request merged**
