### PR TITLE
LibreOffice

### PR DESCRIPTION
**Pull request by DarkknightAK**
Bullet icons
bullet
bullet

### CODE REVIEW

**Comment by staniek** [comment]
Compared to the original LO icons (with arrows), I see a lot of visual
noise; worse -- the triangles as small. Many icons here are similar to each
other.

On 7 February 2015 at 12:48, DarkknightAK <notifications@github.com> wrote:

> Bullet icons
> [image: bullet]
> <https://camo.githubusercontent.com/95a6b46556d0024d2b8ec751708a280d850d43f7/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f313634323435362f7664672f706c61736d612d6e6578742d69636f6e732d776f726b696e672f616374696f6e2f746f6f6c6261722f4c4f2f77726974657242756c6c6574732e706e67>
> [image: bullet]
> <https://camo.githubusercontent.com/2012268314a82bbc0ec31646cbcca29e9c467af0/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f313634323435362f7664672f706c61736d612d6e6578742d69636f6e732d776f726b696e672f616374696f6e2f746f6f6c6261722f4c4f2f77726974657242756c6c6574732d622e706e67>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/NitruxSA/plasma-next-icons/pull/69
> Commit Summary
>
>    - LibreOffice
>
> File Changes
>
>    - *A*
>    Breeze/actions/LO_lc_icons_breeze/lc_bulletsandnumberingdialog.svg
>    <https://github.com/NitruxSA/plasma-next-icons/pull/69/files#diff-0>
>    (131)
>    - *A* Breeze/actions/LO_lc_icons_breeze/lc_decrementlevel.svg
>    <https://github.com/NitruxSA/plasma-next-icons/pull/69/files#diff-1>
>    (116)
>    - *A* Breeze/actions/LO_lc_icons_breeze/lc_decrementsublevels.svg
>    <https://github.com/NitruxSA/plasma-next-icons/pull/69/files#diff-2>
>    (116)
>    - *A* Breeze/actions/LO_lc_icons_breeze/lc_incrementlevel.svg
>    <https://github.com/NitruxSA/plasma-next-icons/pull/69/files#diff-3>
>    (116)
>    - *A* Breeze/actions/LO_lc_icons_breeze/lc_incrementsublevels.svg
>    <https://github.com/NitruxSA/plasma-next-icons/pull/69/files#diff-4>
>    (116)
>    - *A* Breeze/actions/LO_lc_icons_breeze/lc_insertneutralparagraph.svg
>    <https://github.com/NitruxSA/plasma-next-icons/pull/69/files#diff-5>
>    (125)
>    - *A* Breeze/actions/LO_lc_icons_breeze/lc_movedown.svg
>    <https://github.com/NitruxSA/plasma-next-icons/pull/69/files#diff-6>
>    (116)
>    - *A* Breeze/actions/LO_lc_icons_breeze/lc_movedownsubitems.svg
>    <https://github.com/NitruxSA/plasma-next-icons/pull/69/files#diff-7>
>    (116)
>    - *A* Breeze/actions/LO_lc_icons_breeze/lc_moveup.svg
>    <https://github.com/NitruxSA/plasma-next-icons/pull/69/files#diff-8>
>    (116)
>    - *A* Breeze/actions/LO_lc_icons_breeze/lc_moveupsubitems.svg
>    <https://github.com/NitruxSA/plasma-next-icons/pull/69/files#diff-9>
>    (116)
>    - *A* Breeze/actions/LO_lc_icons_breeze/lc_numberingstart.svg
>    <https://github.com/NitruxSA/plasma-next-icons/pull/69/files#diff-10>
>    (125)
>
> Patch Links:
>
>    - https://github.com/NitruxSA/plasma-next-icons/pull/69.patch
>    - https://github.com/NitruxSA/plasma-next-icons/pull/69.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NitruxSA/plasma-next-icons/pull/69>.
>



-- 
regards, Jaroslaw Staniek

KDE:
: A world-wide network of software engineers, artists, writers, translators
: and facilitators committed to Free Software development - http://kde.org
Calligra Suite:
: A graphic art and office suite - http://calligra.org
Kexi:
: A visual database apps builder - http://calligra.org/kexi
Qt Certified Specialist:
: http://www.linkedin.com/in/jstaniek

**Comment by DarkknightAK** [comment]
the style is the same than in the formating toolbar.
formating
in the other styles for bullets are only arrows used, but for the bullet icons (lc_decrementindent) in the formating bar are used other icons. why the result is the same.
you can see here an comparison between the different icon sets.

We can reduce the style but than we should reduce also the icon style for the formating icons. maybe there is to much information on each icon, but if you look at the icon it is clear what the icon is used for in comparison to an arrow, two arrows, ...

**Comment by DarkknightAK** [comment]
I know there are some icons double. I have to link them, but now I make each toolbar and than I make a clean up.

**Comment by DarkknightAK** [comment]
icons for the frame toolbar
frame
frame

**Comment by DarkknightAK** [comment]
basicshape
basicshape

**Comment by DarkknightAK** [comment]
stars stars

**Comment by DarkknightAK** [comment]
shapes
shapes

**Comment by DarkknightAK** [comment]
callouts callouts

**Comment by DarkknightAK** [comment]
flowchart flowchart

**Comment by DarkknightAK** [comment]
arrows arrows

**Pull request merged**
