### PR TITLE
Inherits=Breeze

### PR DESCRIPTION
**Pull request by KAMiKAZOW**
Breeze Dark should inherit regular Breeze and only contain changed icons.

### CODE REVIEW

**Comment by KAMiKAZOW** [comment]
This PR does not delete any icons in Breeze Dark, as you are more qualified than me to know which icons to actually keep.

**Comment by UriHerrera** [comment]
It should but the theme is broken just by setting the line to *Breeze* and using the icons that are different. Some applications don't load their correct icon, folders are broken, System Settings doesn't display most icons, etc.

**Comment by UriHerrera** [comment]
I've cleaned up the Dark theme and organized some icons, I've added the line though some icons still need to be present in the Dark theme.

**Comment by KAMiKAZOW** [comment]
Isn't it just a cache issue? Is it the same even after "rm ~/.kde/cache-localhost.localdomain/*.kcache" and then logging out and in again?

**Comment by UriHerrera** [comment]
No, It just doesn't load them.

**Pull request closed without merging**
