### PR TITLE
Toolbar icons for clementine

### PR DESCRIPTION
**Pull request by varlesh**

### CODE REVIEW

**Comment by Steinhagen** [comment]
These are great! Nice work man! :+1:

**Comment by DarkknightAK** [comment]
nice work will have a look when I am back from vecation. on sunday but look good

**Comment by DarkknightAK** [comment]
and thanks

**Comment by UriHerrera** [comment]
`applications-internet.svg` is a 16px icon, toolbar icons are 22px.

**Comment by varlesh** [comment]
@UriHerrera  Sorry, i was wrong.
applications-internet.svg moved to new folder **categories/start-menu-small** or how? Maybe create symlink on **places/user-folders-small**?
I don't know to why format-indent-more.svg blured ))

**Comment by varlesh** [comment]
I found a mistake . On panel used icons 16x16...

**Comment by varlesh** [comment]
I create new request https://github.com/NitruxSA/plasma-next-icons/pull/248

**Pull request closed without merging**
