### PR TITLE
Update Breeze toolbar icons with flattr-icons (names)

### PR DESCRIPTION
**Pull request by DarkknightAK**
I'm look into the flattr-icons repository and see which icons are still missing in the breeze icons theme. only toolbar icons.
this are the first 28 files. the gtk files will be moved into a separate folder.

### CODE REVIEW

**Comment by DarkknightAK** [comment]
the gtk files from flattr-icons in an separate folder. there are only links to the toolbar icons.

**Comment by UriHerrera** [comment]
Breeze/actions/toolbar/add-files-to-archive.svg - This icon is for File Roller Ark doesn't use it.
Breeze/actions/toolbar/add-folder-to-archive.svg - This is also for File Roller.
Breeze/actions/toolbar/add.svg - Neither KDE or Gnome use it, both use `list-add`.
Breeze/actions/toolbar/address-book-insert.svg - This I think it's for Evolution
Breeze/actions/toolbar/addressbook.svg - This is a wrongly named icon.
Breeze/actions/toolbar/appointment.svg - I have no idea where this is used.
Breeze/actions/toolbar/arrow-top-double.svg - I think this is for Gnome 2.
Breeze/actions/toolbar/back.svg - Another icon with the wrong name.
Breeze/actions/toolbar/bookmark-add.svg - GTK
Breeze/actions/toolbar/bookmark-list-add.svg - GTK
Breeze/actions/toolbar/bookmark-view.svg - GTK
Breeze/actions/toolbar/bookmarks-list-add.svg -GTK
Breeze/actions/toolbar/bookmarks.svg - KDE uses this for the kickoff tabs (no need at this size).
Breeze/actions/toolbar/bottom.svg - Another icon with the wrong name.
Breeze/actions/toolbar/browser-download.svg - GTK
Breeze/actions/toolbar/button-cancel.svg - GTK
Breeze/actions/toolbar/cab_extract.svg -GTK
Breeze/actions/toolbar/cancel.svg - Another icon with the wrong name.
Breeze/actions/toolbar/cdplayer-eject.svg - GTK
Breeze/actions/toolbar/checkmark.svg - I don't know where this is used.
Breeze/actions/toolbar/dialog-apply.svg - GTK
Breeze/actions/toolbar/dialog-no.svg - GTK
Breeze/actions/toolbar/dialog-yes.svg - GTK
Breeze/actions/toolbar/document-info.svg - I don't know where this is used.
Breeze/actions/toolbar/documentinfo.svg - Another icon with the wrong name.
Breeze/actions/toolbar/grk-cancel.svg - GTK
Breeze/actions/toolbar/help-info.svg - GTK
Breeze/actions/toolbar/view-statistics.svg - This is from Oxygen I think, so this is fine.

**Comment by DarkknightAK** [comment]
how do you know so much. I will fix it

**Comment by UriHerrera** [comment]
Breeze/actions/toolbar-apps/collection-refresh-amarok.svg
Breeze/actions/toolbar-apps/collection-rescan-amarok.svg
Breeze/actions/toolbar-apps/download-amarok.svg
Breeze/actions/toolbar-apps/edit-redo-amarok.svg
Breeze/actions/toolbar-apps/edit-undo-amarok.svg
Breeze/actions/toolbar-apps/preferences-indicator-amarok.svg
Breeze/actions/toolbar-apps/preferences-media-playback-amarok.svg

> Amarok should not use its own icons, that's against the guidelines. They should change them.

Breeze/actions/toolbar/filenew.svg - Neither KDE or Gnome use it, both use `document-new`.
Breeze/actions/toolbar/fileprint.svg - Neither KDE or Gnome use it, both use `document-print`.
Breeze/actions/toolbar/filequickprint.svg - Neither KDE or Gnome use it, it's probably a link to `document-print`.
Breeze/actions/toolbar/filesave.svg - Neither KDE or Gnome use it, both use `document-save`.
Breeze/actions/toolbar/filesaveas.svg - Neither KDE or Gnome use it, both use `document-save-as`.
Breeze/actions/toolbar/find.svg - Neither KDE or Gnome use it, both use `edit-find`.
Breeze/actions/toolbar/flip-horizontal.svg - I don't know where this is used. I think Inkscape uses it.
Breeze/actions/toolbar/folder_new.svg - Neither KDE or Gnome use it, both use `folder-new`.
Breeze/actions/toolbar/forward.svg - Neither KDE or Gnome use it, both use `go-forward`.

Breeze/actions/toolbar/player-eject.svg
Breeze/actions/toolbar/player-end.svg
Breeze/actions/toolbar/player-fwd.svg
Breeze/actions/toolbar/player-new.svg
Breeze/actions/toolbar/player-pause.svg
Breeze/actions/toolbar/player-play.svg
Breeze/actions/toolbar/player-record.svg
Breeze/actions/toolbar/player-rew.svg
Breeze/actions/toolbar/player-start.svg
Breeze/actions/toolbar/player-stop.svg

> I don't know what software uses these, but the multimedia-x-y icons are the standard ones.

Breeze/actions/toolbar/stop.svg - This is probably `process-stop`.
Breeze/actions/toolbar/tag-new.svg - A link for `tag`.
Breeze/actions/toolbar/tags.svg - Probably a multiple tags icon.
Breeze/actions/toolbar/top.svg - Neither KDE or Gnome use it, both use `go-top`.
Breeze/actions/toolbar/up.svg - Neither KDE or Gnome use it, both use `go-up`.
Breeze/actions/toolbar/upload-media.svg - This sounds like is used in KDE but I don't know where.
Breeze/actions/toolbar/view-choose.svg - GTK
Breeze/actions/toolbar/window-fullscreen.svg - GTK
Breeze/actions/toolbar/zoom-best-fit.svg - GTK
Breeze/actions/toolbar/zoom-fit.svg - GTK

**Comment by UriHerrera** [comment]
@DarkknightAK I have the names burned into mi mind. :8ball:

**Comment by DarkknightAK** [comment]
:-)

**Comment by DarkknightAK** [comment]
ok in future I'll go through the different apps and search there which icons are still missing. is there a list of gtk specific icons?

good night.

**Comment by DarkknightAK** [comment]
ok. slow down I'll make reasonable pull requests.

**Pull request closed without merging**
