### PR TITLE
change the visible icons to a not to abstract icon

### PR DESCRIPTION
**Pull request by DarkknightAK**
https://phabricator.kde.org/T571

I use this icon also in LibreOffice

Signed-off-by: andreask <kainz.a@gmail.com>

### CODE REVIEW

**Comment by DarkknightAK** [comment]
I'd like to have an feedback if it is ok for you @UriHerrera

**Comment by UriHerrera** [comment]
It isn't abstract.. it literally is layers of objects. I didn't do an eye because it's a pain to do eyes proper.

**Comment by DarkknightAK** [comment]
for layer the icon fits the problem is that sometimes (often) visible on/off is the reason why devs use the icon. for KPasswordDialog the layer icon should work. I will close the comment when the issue was finished discussed in the forum.

**Comment by UriHerrera** [comment]
Why would KPasswordDialog use something called `layer-visible-x` that's the kind of thing that doesn't make sense. Whoever maintains it should be using a different icon for whatever it's using this icon.

**Comment by UriHerrera** [comment]
I've also change the icon to the layers icon like the one you used for Inkscape.

**Pull request closed without merging**
