### PR TITLE
LO icons

### PR DESCRIPTION
**Pull request by DarkknightAK**
3D Settings icons
3d Settings
3d Settings

### CODE REVIEW

**Comment by DarkknightAK** [comment]
I will check the other form icons when I come to LO base.

**Comment by DarkknightAK** [comment]
insert

**Comment by DarkknightAK** [comment]
insert cell

**Comment by UriHerrera** [comment]
I think the 7th and 8th icons are mixed in the first image.

**Comment by DarkknightAK** [comment]
I don't think so. 6. is depth, 7. is Direction for perspective and 8. is lightning (sun), but maybe the sun is to abstract.

**Comment by UriHerrera** [comment]
Oh yes I meant 6th and 7th.

**Comment by DarkknightAK** [comment]
ok nr. 6 is extrusion perspective and nr. 7 is lightning. I don't think that we should mix the two icons, because in the other icon styles it's also a perspective cube and a bulb. I can remove the "sun" with a bulb for nr. 7.

**Comment by UriHerrera** [comment]
Ah ok 6th is ok then but 7th looks like the perspective icon in the original LO icons.

**Comment by DarkknightAK** [comment]
sorry uri now I talk about the wrong icons.

**Comment by DarkknightAK** [comment]
Nr. 6 Depth
depth
Nr. 7 Direction
direction

**Comment by UriHerrera** [comment]
Oh, they're good then.

**Comment by DarkknightAK** [comment]
the 3d icons are sometimes tricky. I can make the direction icon into another direction than it is maybe more clear
direction

**Comment by DarkknightAK** [comment]
tools

**Comment by DarkknightAK** [comment]
thanks for the feedback uri and good night.

**Comment by UriHerrera** [comment]
You may want to make the euro logo yourself it looks blurry,

**Comment by DarkknightAK** [comment]
jup I have to renew it.

**Comment by DarkknightAK** [comment]
euro

**Comment by DarkknightAK** [comment]
euro

**Comment by DarkknightAK** [comment]
picture

**Comment by DarkknightAK** [comment]
connectors

**Comment by DarkknightAK** [comment]
lines

**Pull request merged**
