### PR TITLE
LO Base icons

### PR DESCRIPTION
**Pull request by DarkknightAK**
Signed-off-by: DarkknightAK <kainz.a@gmail.com>

### CODE REVIEW

**Comment by DarkknightAK** [comment]
standard

**Comment by DarkknightAK** [comment]
align

**Comment by DarkknightAK** [comment]
shrink

**Comment by DarkknightAK** [comment]
resizing

**Comment by DarkknightAK** [comment]
form

**Comment by DarkknightAK** [comment]
formating

**Comment by UriHerrera** [comment]
On the last image, is the blue border around the selected tool button part of the icon or it's colored by the software?.

**Comment by DarkknightAK** [comment]
sorry this is the hicontrast icon the breeze icon is missing. will ship it.

**Comment by DarkknightAK** [comment]
I'm now nearly finished with the large icons so I start with the small icons and after that I will look at the special files outside the cmd folder.

**Comment by DarkknightAK** [comment]
648 icons that's a mass yeah :-)

**Comment by DarkknightAK** [comment]
formating

**Comment by DarkknightAK** [comment]
zoom

**Comment by DarkknightAK** [comment]
find

**Comment by DarkknightAK** [comment]
movie

**Comment by DarkknightAK** [comment]
Hi Uri, if you have any recomandation please merge I will make a break between small and large icon size

**Pull request merged**
