### PR TITLE
New folder structure

### PR DESCRIPTION
**Pull request by DarkknightAK**
more like nitrux and flattr

Signed-off-by: andreask <kainz.a@gmail.com>

### CODE REVIEW

**Comment by DarkknightAK** [comment]
I know the index.theme file have to be changed and the linked files and breeze-dark. what do you think? a lot of contributors have problem with the size AND with gtk, kde, ... it is nicer to understand for what the icons be used for.

**Comment by UriHerrera** [comment]
Push all changes, otherwise it's going to brake the theme.

**Comment by DarkknightAK** [comment]
hi

I know I only want to ask you before I change everything and you say not a good idea.

with plasmoid I have to look what I can do not happy now.

**Comment by UriHerrera** [comment]
I'm fine with the change but the description of folders in the index.theme file should be kept.

**Comment by DarkknightAK** [comment]
about plasmoid icons. why do they have all different sizes. are they only for ONE plasmoid, because when the icons are plasmoid specific I should make one subfolder per plasmoid instead of group the icons according to the size.

**Comment by UriHerrera** [comment]
> about plasmoid icons. why do they have all different sizes.

The folder `system-power-application` has icons that are standard icons, I did have them on the apps folder, then you moved them there because I mentioned that they're used in Homerun kicker. They're not specific to a plasmoid.

The folder `media-album` is just an icon that was requested for that plasmoid because it was using an Oxygen asset, it's not part of the theme.

The folder `kickoff-menu-tabs` is for the icons that Kickoff used in Plasma (1/4). The Plasma theme now provides those icons instead of the icon theme.

**Comment by DarkknightAK** [comment]
for the plasmoid icons I will discuss this with the plasma devs. don't know if it is better to have the plasma icons in breeze or in plasma but I prefere one place for all.

**Comment by DarkknightAK** [comment]
From my point of view the pull request is finished. as it is an big change (only in structure) I would prefer you merge the request. thanks.

**Comment by UriHerrera** [comment]
I've applied your changes and some more so I'll close the pull request because now it's conflicting.

**Pull request closed without merging**
