### PR TITLE
LO Icons

### PR DESCRIPTION
**Pull request by DarkknightAK**
LO Draw Position icons
position icons
I make the icons without the blue, because you don't need the color to understand the icons. but when you like, I can add the color again.
More LO icons will come (I push them with a preview so that it is easier to say does fit or not)

### CODE REVIEW

**Comment by DarkknightAK** [comment]
align object
one align object icon was missing

**Comment by DarkknightAK** [comment]
LO draw zoom toolbox hicontrast and breeze
zoom hi contrast
zoom breeze

**Comment by DarkknightAK** [comment]
ok now all icons have the right size. if the icons will work, please merge the pull request.

**Comment by DarkknightAK** [comment]
standard toolbar


the icons from the first drop-down icon is in the LO folder res and not cmd. would it be possible to rename the LO_lc_icons_breeze to LO and make there the subfolder structure from LO.

**Comment by DarkknightAK** [comment]
Can we make the folder structure from the LO icons?

**Comment by UriHerrera** [comment]
How's that folder structure?

**Comment by DarkknightAK** [comment]
-avmedia
--16
--24
-chart2
--5260
--32
-cmd
--24
--16
-database
-dbaccess
-desktop
-extensions
-formula
-fpicker
-framework
-padmin
-reportdesign
-res
-sc
-sd
-sfx2
-starmath
-svtools
-svx
-sw
-vcl
-wizards
-xmlsecurity

the mail folder structure the subfolders would be for the resolution. you can find the structure also in your theme folder (/usr/share/libreoffice/share/config/)

**Comment by UriHerrera** [comment]
That seems to messy, no, let's keep it like we have it now.

**Comment by DarkknightAK** [comment]
:-) that's messy. where should we move the icons that are not from cmd. they have sometimes really strange names (av02051)

**Pull request merged**
