### PR TITLE
move the lc_ files into the new subfolder large

### PR DESCRIPTION
**Pull request by DarkknightAK**
move the lc_ files into the new subfolder large. the new (future) sc_ files will come to the subfolder small. for special files additional subfolders will maybe needed in future. I don't want to have > 1000 files in one folder.

the main folder was renamed to LO_icons_breeze because there are more than lc_ files included.

### CODE REVIEW

**Comment by DarkknightAK** [comment]
new structure

**Comment by DarkknightAK** [comment]
arrows I was ill the last days.

**Comment by DarkknightAK** [comment]
circles

**Comment by DarkknightAK** [comment]
comments

**Comment by UriHerrera** [comment]
The folder names should be more descriptive because while the names are explained in the wiki for the main theme they're not for the LO icons.

**Comment by DarkknightAK** [comment]
16x16 and 26x26 ?

**Comment by UriHerrera** [comment]
Yeah :)

**Comment by DarkknightAK** [comment]
Any additional recommendation? the folder name is now 16x16 and 24x24 I think this is a good solution.

**Comment by UriHerrera** [comment]
The last icon in the comments image, the bubbles look squashed. Keep their aspect ratio proper and cut one of them where they intersect.

**Comment by DarkknightAK** [comment]
annotion

**Comment by DarkknightAK** [comment]
Uri, thanks that you make the design review. It is very useful for me.

**Comment by DarkknightAK** [comment]
Any questions for a push?

**Pull request merged**
