### PR TITLE
Floppy icon device/sidebar see #149 and folder-open icon #151

### PR DESCRIPTION
**Pull request by DarkknightAK**
Signed-off-by: andreas_ka <kainz.a@gmail.com>

### CODE REVIEW

**Comment by DarkknightAK** [comment]
work in git coca and is the same icon than document-open-folder with the folder size.

**Comment by UriHerrera** [comment]
The folder-open needs to be in the 64px size too though, I think that's what he meant when requesting it.

**Comment by DarkknightAK** [comment]
Uri have you any comment, or can you merge this request?

**Comment by UriHerrera** [comment]
Yes,

Weren't the small colored folders if Breeze Dark was used? or why did you added them there too.

The open folder has a different perspective than all the other icons. Just lower the front.

**Comment by DarkknightAK** [comment]
in breeze dark there are colored folders in places in large size but not in small size. why? when you have to use the icons from the breeze (light) theme than the colored folders should also be removed from Breeze Dark/places/user-folders/ not only from /user-folders-small

**Comment by DarkknightAK** [comment]
I don't know how the breeze dark folder works. are there duplicates?

**Comment by UriHerrera** [comment]
Breeze Dark inherits the icons that are not in in its folders from Breeze (that's in the index.theme file) . The line `Inherits=` allows a secondary theme to use icons it doesn't have so that files aren't duplicated.

**Comment by DarkknightAK** [comment]
does it work now? I can also close the pull request and make single requests if you like.

**Pull request merged**
