### PR TITLE
Added status icons for Dropbox

### PR DESCRIPTION
**Pull request by s-kostyuk**
Created new status icons for official Dropbox client based on original outlined Dropbox logo: [see here](https://www.dropbox.com/s/bt6o5yzknsq1nj1/dropbox-glyph-outline-blue.pdf?dl=0). Icons in action:

>Just logo:
>logo

>Synced:
>idle

>Sync in progress:
>syncing

But, honestly, result is not so good as may be: it isn't pixed-perfect at all, haves a lot of bias lines, looks smaller comparing with other icons on the panel

So, fell free to decline this pull-request if you aren't satisfied with results. And consider this pull request as an icon request

### CODE REVIEW

**Comment by DarkknightAK** [comment]
thanks for contribute I'll check them. in muon i use for installed another icon so maybe I will update yours to be consistent.

**Comment by UriHerrera** [comment]
Try to align the lines that do fit the grid and transform them according to the logo. Inkscape has a `View icon` pane too, use it.

Otherwise, don't make a line icon make it solid.

**Comment by s-kostyuk** [comment]
@DarkknightAK, thank you and @UriHerrera for your work.

Made icons slightly bigger, tried to align their elements without screwing up of the original proportions, backported to Breeze Dark pack

**Comment by UriHerrera** [comment]
Checked one of the icons; Please do not scale them like that, they should be aligned to the pixel grid and also do not use strokes, use fills. See the image below:

**Comment by s-kostyuk** [comment]
Frankly speaking, I haven't significant experience with Inkscape and inspiration to continue work on this icon and don't squire everything up again :). So, let's try one more time...

P.S. Looks like that the first version of icons (commit 75ff308) was closer to the truth: [1st_version_syncing.png](https://cloud.githubusercontent.com/assets/5122578/8993364/440354e8-370d-11e5-969a-3c5ce0fe7473.PNG)

**Comment by UriHerrera** [comment]
It was but it wasn't completely aligned and you used strokes ;)

**Comment by s-kostyuk** [comment]
OK, check this out

Previews: 
* [fail.png](https://cloud.githubusercontent.com/assets/5122578/9008613/254815d8-37a4-11e5-9641-3db172b76f63.png)
* [idle.png](https://cloud.githubusercontent.com/assets/5122578/9008612/25476084-37a4-11e5-8709-e7d035f0da3b.png)
* [logo.png](https://cloud.githubusercontent.com/assets/5122578/9008615/2557a336-37a4-11e5-989c-38c21a824cea.png)
* [syncing.png](https://cloud.githubusercontent.com/assets/5122578/9008614/2551db0e-37a4-11e5-8f85-948f3971979d.png)

**Comment by UriHerrera** [comment]
The extra glyph in `fail` and `idle` is not matching the position of `syncing`.

**Comment by s-kostyuk** [comment]
Updated positions of glyphs. Demonstration (three icons merged):
all

But glyphs looks worse now in ``View icon`` pane, comparing to c1676dc

**Comment by UriHerrera** [comment]
For those you can use the `dialog-apply` or` dialog-ok`and `window-close` icons and cut them.

**Comment by s-kostyuk** [comment]
Sorry, I'm quitting. Too much time was wasted on this icon and I can't be sure that I will do everything exactly as you imagined and asked. Please, do everything as needed, based or don't based on my work above.

This pull request will be closed next week, repository - after two weeks

**Pull request closed without merging**
