### PR TITLE
missing gtk2 icons

### PR DESCRIPTION
**Pull request by DarkknightAK**
used for example in firefox
right click on tab undo close tab

Signed-off-by: andreask <kainz.a@gmail.com>

### CODE REVIEW

**Comment by UriHerrera** [comment]
The icons in the context menus are 16px both for GTk and Plasma

**Comment by DarkknightAK** [comment]
so than I will make 16 icons.

**Comment by DarkknightAK** [comment]
the thing is that breeze offers as standard 22 px icons for toolbar and for menu bar so I make them all 22 px

**Comment by UriHerrera** [comment]
Not all the icons for the toolbars are used in the context menus only some like new file, save, folder and similar.

**Pull request closed without merging**
